package transferobjects;

import java.sql.Timestamp;
import java.util.Map;

/**
 * Data Transfer Object for Report entity in the PTFMS system.
 * Represents generated reports including analytics, performance metrics,
 * financial summaries, and operational reports. Used to transfer
 * report metadata and content between application layers for
 * business intelligence and decision-making purposes.
 */
public class ReportDTO {
  /** Unique report identifier */
  private int reportId;
  /** Report title */
  private String title;
  /** Report type (FLEET, MAINTENANCE, FUEL, OPERATOR, GPS) */
  private String reportType;
  /** Report data as key-value pairs */
  private Map<String, Object> data;
  /** User who generated the report */
  private int generatedBy;
  /** When the report was generated */
  private Timestamp generatedAt;
  /** Report period start */
  private Timestamp periodStart;
  /** Report period end */
  private Timestamp periodEnd;
  /** Report format (HTML, PDF, JSON) */
  private String format;
  /** Report status */
  private String status;

  /**
   * Get the report ID
   * 
   * @return the report ID
   */
  public int getReportId() {
    return reportId;
  }

  /**
   * Set the report ID
   * 
   * @param reportId the report ID to set
   */
  public void setReportId(int reportId) {
    this.reportId = reportId;
  }

  /**
   * Get the title
   * 
   * @return the title
   */
  public String getTitle() {
    return title;
  }

  /**
   * Set the title
   * 
   * @param title the title to set
   */
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * Get the report type
   * 
   * @return the report type
   */
  public String getReportType() {
    return reportType;
  }

  /**
   * Set the report type
   * 
   * @param reportType the report type to set
   */
  public void setReportType(String reportType) {
    this.reportType = reportType;
  }

  /**
   * Get the data
   * 
   * @return the data
   */
  public Map<String, Object> getData() {
    return data;
  }

  /**
   * Set the data
   * 
   * @param data the data to set
   */
  public void setData(Map<String, Object> data) {
    this.data = data;
  }

  /**
   * Get the generated by user ID
   * 
   * @return the generated by user ID
   */
  public int getGeneratedBy() {
    return generatedBy;
  }

  /**
   * Set the generated by user ID
   * 
   * @param generatedBy the generated by user ID to set
   */
  public void setGeneratedBy(int generatedBy) {
    this.generatedBy = generatedBy;
  }

  /**
   * Get the generated at timestamp
   * 
   * @return the generated at timestamp
   */
  public Timestamp getGeneratedAt() {
    return generatedAt;
  }

  /**
   * Set the generated at timestamp
   * 
   * @param generatedAt the generated at timestamp to set
   */
  public void setGeneratedAt(Timestamp generatedAt) {
    this.generatedAt = generatedAt;
  }

  /**
   * Get the period start
   * 
   * @return the period start
   */
  public Timestamp getPeriodStart() {
    return periodStart;
  }

  /**
   * Set the period start
   * 
   * @param periodStart the period start to set
   */
  public void setPeriodStart(Timestamp periodStart) {
    this.periodStart = periodStart;
  }

  /**
   * Get the period end
   * 
   * @return the period end
   */
  public Timestamp getPeriodEnd() {
    return periodEnd;
  }

  /**
   * Set the period end
   * 
   * @param periodEnd the period end to set
   */
  public void setPeriodEnd(Timestamp periodEnd) {
    this.periodEnd = periodEnd;
  }

  /**
   * Get the format
   * 
   * @return the format
   */
  public String getFormat() {
    return format;
  }

  /**
   * Set the format
   * 
   * @param format the format to set
   */
  public void setFormat(String format) {
    this.format = format;
  }

  /**
   * Get the status
   * 
   * @return the status
   */
  public String getStatus() {
    return status;
  }

  /**
   * Set the status
   * 
   * @param status the status to set
   */
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * String representation of the report
   * 
   * @return formatted string with report details
   */
  @Override
  public String toString() {
    return "Report [ID=" + reportId + ", Title=" + title + ", Type=" + reportType +
        ", GeneratedAt=" + generatedAt + ", Status=" + status + "]";
  }
}
